apiVersion: v1
kind: Secret
metadata:
    name: alertmanager
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:ABQ2x83Ew92vyoMAAfRg3bDyqKmDK+8A6b0Bu4nb0jLEeEKokY65ULfHu32/RnZSqjuq94WQ4kIe3CsFO3xlYyQy6svmEihhadivaUNB893W0CAo9Zs12Wq8N0HZYGkuBtaLrmWcL4mGUYNaGzeSfurT0/Le7Ymu/w==,iv:4m93Bj7axKA3B6m8/UfaJuCHICrVeN/j64I7J0mbcGU=,tag:q0fqhJkR54hBIPBr9MCzSA==,type:str]
sops:
    age:
        - recipient: age1nk8j4vujprxg5ep7vlgektc8wndmywh9lx4yl5k3flfxdnf9t4xqlu745k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtb0k3dUx1Tm9OY1ZqT3h6
            MU1SdXFIMC9oSkhnLzIwTFBoYXp1WG1XajN3CnJ3RTBEUzNPSUhwRVV6WXJxbzNw
            RTlsSDlJa09ma3N6WWJoQWd4Z2VYaWsKLS0tIE16cmx5QnFhby9tdXFYYnd1SWVO
            YnRzdzlLTEwvU21WSkxLRUtvQVNlb1EKNE5izoOzXzy4CSeELga52JQ1T6yjOx4z
            Kb72Z0RB3GPtRy6EaIGW6VAQ0iMKiB2OT3rk2DJp0tkn9Q4Mz1a0Mw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-22T06:33:53Z"
    mac: ENC[AES256_GCM,data:6FZLWOudm41I0exiRRhQHT3npIh6AFS+fvAAmQYq0YEkl+1PJX7maFdcp7RVJwclFkxtXfHOFfCUB9ptuqhq2FbF/EJCWoqqCSP9DyqTUMy/61a4w6oDfxQxWxHklWGHy78PcbYonNgtPM53S0vps+ialeAJ1BHNIZChgyJtYvg=,iv:o8DZlwvYE8XmHpyA1v5Aut6V0UmueHHeAAZcGoIrj1M=,tag:eKulxfN0uxi9CcbIcttiLQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
