apiVersion: v1
kind: Secret
metadata:
    name: alertmanager
stringData:
    discord-webhook-url: ENC[AES256_GCM,data:ZA54zrz79OrNyJyrmMESW14VeK7Qo3mxGuB+VJ2iwXe8udqDAt9fmLAa49pnMVNdTKv7yKF22OV3aqu/PyI9RY7ch2OLvTTs+U6oEmRkln7xouN3wK27tXzBart5mqMyBmq62p2q6/XG8Nvk6RH8+N4Zczts5evL8A==,iv:iVxj5+PnLHTdu+7447KZKAfYsTeL9rWQMysRgRmcIls=,tag:nrnua0xMGW2M2lF4KewZnQ==,type:str]
sops:
    age:
        - recipient: age1nk8j4vujprxg5ep7vlgektc8wndmywh9lx4yl5k3flfxdnf9t4xqlu745k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtQmRNRVdsNVJ6OG9RYzQy
            enVodFNFcVBIVGJEdDJpTFJiWGFoOUl1cGwwClUvTUlpU0J3SjZ5eHovTFB1Z0Ns
            eSt1cFR4VHJnTTNlMGVsbnVmM0NTSDQKLS0tIHFpdXYxb3ZwR0Q1b25sM2JTbXFq
            d3Rwd2Z4Q1hVeW92Q1k5b2laQklNRzgKgc6clvI3C5PX6eR181ou7lj2jvQFCJfP
            KS14gCmgx69Ll25/dqOhssiOh+b8CsX8Xj7oGxJy4mYzNvoXJX0j9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-22T07:11:05Z"
    mac: ENC[AES256_GCM,data:YagefwPbDNsX7wLpKZDPW0rQYR3uuF1w6G2h2UP+iaH8gQVP4Ba+ZIZElBHpfQRGjZys++0ZNNQUTAk7VFib38JYIPSXtLw2PfzUulEAQldLIT+lCRXTYxJFMsaobgNEoItWTb+QG9k2HK+zoVVxu0YBRSNuTTj0qkaXG2bBYUg=,iv:0Uqlm3ZscR5dNZ8OtaYFIOLQcZ3RPTGkEsBgKD7h/64=,tag:UKNpU2nmOUT7nqITQpBdNw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
