apiVersion: v1
kind: Secret
metadata:
    name: lake-app
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:4AoT,iv:BfSJO61OokCLwXNdDuPKR4gxftfWJaqk8/PPSY1mtpY=,tag:6NbnRKWSDfk4xIa6gCLY6g==,type:str]
    password: ENC[AES256_GCM,data:oqJlLF8L6g==,iv:gEgd2O7vG4k8ocM8GTEu3U6nbwr/5N7IrpQiWsEH3P8=,tag:tY6lfYVzSPICJNMM4A4Xbw==,type:str]
sops:
    age:
        - recipient: age1nk8j4vujprxg5ep7vlgektc8wndmywh9lx4yl5k3flfxdnf9t4xqlu745k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3d1VTTDR2VjBMMlgyQkFs
            Q1MyUXBNK3BTcHBvN2FQTG16bjNlZnQ1YlhvCkxQT3RjZmRaeTAzYUJhVE5IRzVk
            bkJXMGRjTlJrVGVoQ1EyMDBZdFBhdjAKLS0tIFN2dnA0STBaa01ZL0xTbCt5NDRq
            bi9xNXNaNUVLTk82M2lYeTYvSmlwelEKXPYuc24G1s15CX+03d6dFE5V7e/pk5ci
            tMwCMJViRfK176ZICoPSiQ1gfKABZL4R7xs6k+l8F1bJvLnQnqSJ+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-26T20:53:40Z"
    mac: ENC[AES256_GCM,data:3evmum5A9KBqxfGoOaIoqNPrGJ9/ufaWJ9gEINAehRKmMDlTV+nqKkDl3ZK5dGsnz61qgSCunE395LdTEgSAA6CsZGHtrsT4LQxL5ac/D/V2Wt40s01KZxDs1JyM/26GHYZBNfHWQIdlmGzPQ/PfCIaVEEiMjRI+szSqG+1A89g=,iv:wYc4eaakZUMh1Z50irjL5PyKojtC8G+acmx9sgS6GwM=,tag:3eP0bL3j6SDNRxkNXB2oOw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
