apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
buildMetadata: [originAnnotations]
resources:
  - alertmanager.yaml
  - alloy.yaml
  - grafana.yaml
  - kube-prometheus-stack.yaml
  - restic-exporter.yaml
  - speedtest-exporter.yaml
