apiVersion: v1
kind: Secret
metadata:
    name: restic-exporter
type: Opaque
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:SyBIvuGRGeIVQbUWNJC4ttEefn0=,iv:NWHc+0nuojk5zCyIa1qK7aqzy8sWsPYkn0nuKbEaobQ=,tag:PeVxQ5W6EfOHLP6Gbsqp+A==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:DnF9jo+8VlQ+Dw1J,iv:64D21OZ+V2UgwF49tol/5ivsD73FmI5zT1DVKjSOsk8=,tag:cMgBEE3RLHXRvZkzwjKQpQ==,type:str]
    B2_ACCOUNT_ID: ENC[AES256_GCM,data:7H5fcL98XwQ3oQ4bqngjTg0vltpw453H8w==,iv:WXbRSzpk+IvXV53A9l6avpf0EY8q61/C1eCLTTKIxlw=,tag:TvhTnWW3kv3vNSdD0Idh8w==,type:str]
    B2_ACCOUNT_KEY: ENC[AES256_GCM,data:AuuUKgpy8542p3osH3gAFiK1nkAxhLaT3eSedxL0vA==,iv:kUN4wOUDzzflxcb0qINF5EvcqB0UnrD59s1weCHjlHk=,tag:dRPB+msTMMOE2tZNevAv7A==,type:str]
sops:
    age:
        - recipient: age1nk8j4vujprxg5ep7vlgektc8wndmywh9lx4yl5k3flfxdnf9t4xqlu745k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJaDVOU2FLUFdqQndwYTlq
            a0xUTnVyWGF5WkVUVVAraHB3aEdRV3c4ZTFrCm5qbzl4RjJyM1ZBWEdJR1lSWENE
            UWcrZUYySVJVcU1BVml0Y3pNRGg5MlUKLS0tIDBEQmZNNUJyTnZuMG9tNjhoaDBF
            dWNzN1dqUGgzd2U1RlUzdVRoaUZoK1EKjAATPsROe7fThOnxOhHtNgYl8jfbItr+
            +wvaMKl31J6ic03yrlb/RhNE+n8HsulPiw6mauinQD0OFzHfOrGqBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-05T04:40:49Z"
    mac: ENC[AES256_GCM,data:vIXuDX/vRS4PMLLcxl08HQOReMP3rJMen+91CIGi8FwIsjQq0GZ9XhrrvlNLciwU6z9E/j53nXSsFhr0NLCoUsaHc+CQBF+rlLuUsQ4XlSvYCEia+bIxWAWAHaemdcM8NJRqT404FQpKsVX8zXFB3TXwmGt3EuksLEUC5gFmZAU=,iv:nKpPL7XWkuG07BqWTXj0reyIZ32Sb22+XYehRucZw7o=,tag:USOTYjMW42ecckQutRHc2w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
