---
roles:
  - name: ansible-restic
    src: https://github.com/angristan/ansible-restic
    version: 535396963a6d5269375c95d271e7d0d8b9f21695
  - name: ansible-rclone
    src: https://github.com/stefangweichinger/ansible-rclone
    version: a882d5b91e91e1fb599dead4713cbf8e21a6483c
  - name: geerlingguy.node_exporter
  - name: ansible-systemd-timers
    src: https://github.com/vlcty/ansible-systemd-timers
    version: 965dbcf35e596c0e8784ab8adf636ae3e3139da9
