apiVersion: v1
kind: Secret
metadata:
    name: gickup-github-token
    namespace: default
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:lPSDFvqo4/mhVdh6v+doQVN/0ZguaUbpH749spFqcrk6P6bDXT/5zU4PkSUWtDf7l3Hti2rYQYUkm60+6gpxqvx/crLcpyZx3J+EBaVTW9tGkJ/SwUeNlVLxgnua,iv:Ps9ga9eySXCskq6M6w2e9vDf15ZFBQjtBdy/uCcXcKU=,tag:DCq//E31MgQu04LcgKXeLA==,type:str]
sops:
    age:
        - recipient: age1nk8j4vujprxg5ep7vlgektc8wndmywh9lx4yl5k3flfxdnf9t4xqlu745k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArRGhBVG5pTUQvSzlic3lt
            SUsyYURsTjVvcVNwdmJ5aktqdnFEaVNxWUNFCkNJQWtEVkM4Ymd1VUVITHBwN0hT
            aWI2Q3graWxuRlU3Ylh4SGgwallzZm8KLS0tIE13Vkw5aEVDajhZZHNrY0NOY3V1
            bEg2bnFUa0o5QW9Za0thTkRJMTZXOW8Kp/bChywS/9cylE6sUwii6D3W0/3vTivg
            +LFIyW8hzt9hsh47+ol9TJMmqkSk/6n697CpuseK2bjb6aSu9YboQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-22T10:14:37Z"
    mac: ENC[AES256_GCM,data:BSN/I/I/NuMFnqL/kcYEoTN2K0DppEwFQnieudLJEEGEJaGw4HkwjP2bp7+rsYhcO6pPQPk0oaavdziOH80AatYLcUEuT5ThGV62KwXEjXAgwwNf2YPmUA9RzxZyUWYroZmHbzx0iG+elESkZfGHEoVCtN8BfLX+1RmtaKt59dk=,iv:kTwSPypoafMrVMPUxKzqK0pl6tfnBpjxkCNwS2zZefY=,tag:QL+z7kKKugUWbd81aD4H1g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
