apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
buildMetadata: [originAnnotations]
resources:
  - actual.yaml
  - charali.yaml
  - echo-server.yaml
  - fresh-rss.yaml
  - gickup.yaml
  - homepage.yaml
  - ittools.yaml
  - lubelogger.yaml
  # - paperless.yaml
  - radicale.yaml
  - searxng.yaml
  - silverbullet.yaml
