apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    HOMELAB_DOMAIN: ENC[AES256_GCM,data:CUr1eFc+lEakh8Q=,iv:DCHfR8vPYR80TVVDQ8k6RJom5IYfKovRlBKdZBKrQXM=,tag:jS96h+L7O5rjkqo8uJ9Idg==,type:str]
    PUBLIC_DOMAIN: ENC[AES256_GCM,data:+5mzJaT4gJKl9uRwiyaz,iv:NX7vE3fvyZfLzeb+jWL1o+/BjAfUzvtx8HircSoNiR8=,tag:BH5ZrhZZLYVmCTP8xMocWg==,type:str]
    ADMIN_EMAIL: ENC[AES256_GCM,data:JZEPqw3ePTezoRsbfP6ose3mQs5rWFE=,iv:NL1HtZS9BoV3W0H59TCZTZFVmAm3tXGH4b6yX0NNb84=,tag:dhE5TbJ/j9PTkSDBAKD3mw==,type:str]
    CF_ACCOUNT_ID: ENC[AES256_GCM,data:uEoCmqGrJEuDUBSPCgzoxp6eeCg5OEeSUZWK8Fr//+s=,iv:UWIo9vziXncZM4DOg47pC+r3sVw0wzqqiT7vo1Foon8=,tag:UOqJ+W0cEXpz2tIAgg5J0Q==,type:str]
    CF_TUNNEL_ID: ENC[AES256_GCM,data:6YQmCTzs0bpzORCP2uRavocdXrf0zcjnbmOO0NFagBAhgICD,iv:MzsLdnBWLyiDIuJlCoq/bnvEFF1XgdzjIKmON50unrE=,tag:IimhYtGxDruUqDu0mbpo6A==,type:str]
sops:
    age:
        - recipient: age1nk8j4vujprxg5ep7vlgektc8wndmywh9lx4yl5k3flfxdnf9t4xqlu745k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVMk9PKzFWZFVWNjVKWVRm
            YWV0V1dMM2ZMWlVCZVNkWExMcGEwdjZKUERjClhqcERPYWdvajJ4N3M1cWdKVTdW
            VXA4R2gxRTB5bDdVRVpKekluOEFoQ1UKLS0tIG9RUlcwNmtHNzdSTWNxaWpvSm5V
            bTN4dzBBUTQrU25Oak5QQVVZcE13RzAK7gY/rg+2ezDvrN+VVn/3nmpx5cOc2a4K
            yUfJXnDNophLvNBrkhar1wtjOIcdaefJ7L3m7HYmlg5+2/K30RtErA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-22T07:04:15Z"
    mac: ENC[AES256_GCM,data:PIkcKOc8I9/NcD4JyIT/zCpjlAk+UMw2Kj+A/MHcYheuG8whP6Oi6HBdX4gVEeeuUk/JwYt3atCDr/ZV4AxD65qdGKSfZM/YCxGFwj+vCtaNQwBOLZXSlAqzwjKQQ4XWvjBxU0MmFmqvBlg+vrPTwHKJt3zC1NLaVcvgjMZmgyw=,iv:WyS3jpCMxYJMKOp3P6aQXL6+jt08EvvVmdtyYPRQpwU=,tag:A6kucSs3feik+qlSBjmnmA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
